### ISSUE TITLE
GwtMockito master is broken with Gwt > 2.6 due to use of internal class HistoryImpl

### ISSUE THREAD

**Issue by fgalassi** [google/gwtmockito#49]
Gwtmockito makes use of GWT class HistoryImpl (https://gwt.googlesource.com/gwt/+/2.6.0/user/src/com/google/gwt/user/client/impl/HistoryImpl.java) but the class was removed and made private in Gwt 2.7.x (https://gwt.googlesource.com/gwt/+/2.7.0-beta1/user/src/com/google/gwt/user/client/impl/) so it errors out.

**Comment by ekuefler** [comment]
Thanks for the report. Looks like history support is simpler in 2.7, so this only required removing a bit of code. I've uploaded a new snapshot if you want to try it out, or I'll probably release the next version in a week or two if no one reports any problems.
