### ISSUE TITLE
Release 1.1.5 version

### ISSUE THREAD

**Issue by mocleiri** [google/gwtmockito#52]
I need access to the recently commited changes for mocking RadioButton's

I've tested locally against the snapshot and it works (great for validating my widget) but I need a real release made so that I can commit my code against my local project since we have a rule against using -SNAPSHOT's

Would it be possible to make a new release that contains the most recent fixes?

Thanks

**Comment by ekuefler** [comment]
I've just released 1.1.5. It should be on Maven Central in a few hours. Let me know if you see any problems.

**Comment by mocleiri** [comment]
The artifacts are on maven central now.  

Thanks for your fast turn around on this issue, its very much appreciated!
