### ISSUE TITLE
Better GWT unit testing http://google.github.io/gwtmockito hyperLink

### ISSUE THREAD

**Issue by vedsarkushwaha** [google/gwtmockito#67]
Please change the URL.
Add http behind the URL link.

**Comment by ekuefler** [comment]
@gkdn - this looks like it's referring to the link in the repo description, which currently goes to http://google.github.io/gwtmockito%20 - the trailing space needs to be removed. It can also be changed to HTTPS. I don't seem to have permission to update this field, could you change it or point me towards someone who does?

Thanks for pointing this out @vedsarkushwaha

**Comment by gkdn** [comment]
Fixed it. I think I also gave you the permission but let me know if that is not the case.
