### ISSUE TITLE
gwtmockito v1.1.9 is not available in public repos

### ISSUE THREAD

**Issue by epeee** [google/gwtmockito#84]
First of all thx for working on gwtmockito 1.1.9 and doing a new release.
I just tried to use it and it looks like it is not available in public repos (jcenter, mavencentral), isn't it?

**Comment by ekuefler** [comment]
Sorry for that, a bunch of stuff seems to changes around the Maven release process and it took some time to get it set up again. It should be there now.

**Comment by wilkko** [comment]
gwtmockito-parent still missing?

https://search.maven.org/search?q=g:com.google.gwt.gwtmockito

**Comment by ekuefler** [comment]
Sorry, missed uploading the parent. It should be there now: http://repo1.maven.org/maven2/com/google/gwt/gwtmockito/gwtmockito-parent/1.1.9/
