### ISSUE TITLE
Release 1.1.9 is incomplete in maven repository

### ISSUE THREAD

**Issue by lgemeinhardt** [google/gwtmockito#87]
The release 1.1.9 references a 1.1.9 parent, but this is missing in the maven repository (1.1.8 is latest)...

```
<parent>
  <groupId>com.google.gwt.gwtmockito</groupId>
  <artifactId>gwtmockito-parent</artifactId>
  <version>1.1.9</version>
</parent>
```

https://search.maven.org/classic/#search%7Cga%7C1%7Cgwtmockito

**Comment by ekuefler** [comment]
Good catch, thanks. Should be there now: http://repo1.maven.org/maven2/com/google/gwt/gwtmockito/gwtmockito-parent/1.1.9/
